import type { IUser, IKPIRecord } from '../../core/models';

// Mock Users
export const mockUsers: IUser[] = [
  {
    id: '1',
    username: 'employee1@gmail.com',
    name: 'Trần Văn Bình',
    role: 'employee',
    department: 'Kinh doanh',
    token: 'mock-token-employee-1',
  },
  {
    id: '2',
    username: 'manager1@gmail.com',
    name: 'Nguyễn Thị Lan',
    role: 'manager',
    department: 'Kinh doanh',
    token: 'mock-token-manager-1',
  },
  {
    id: '3',
    username: 'hr1@gmail.com',
    name: 'Lê Văn Hùng',
    role: 'hr',
    department: 'Nhân sự',
    token: 'mock-token-hr-1',
  },
  {
    id: '4',
    username: 'ceo1@gmail.com',
    name: 'Phạm Minh Tuấn',
    role: 'ceo',
    department: 'Ban Giám đốc',
    token: 'mock-token-ceo-1',
  },
];

// Mock KPI Records
export const mockKPIRecords: IKPIRecord[] = [
  {
    id: 'KPI-2026-KI-001',
    employeeId: '1',
    employeeName: 'Trần Văn Bình',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    year: 2026,
    quarter: 1,
    period: 'quarterly',
    status: 'draft',
    targets: [
      {
        id: '1',
        title: 'Đạt doanh số cá nhân quý & năm',
        description: 'Hoàn thành chỉ tiêu doanh số được giao cho từng quý và cả năm',
        weight: 50,
        target: '500 triệu',
        unit: 'VNĐ',
        category: 'Doanh số',
        currentValue: 325000000,
        completionRate: 65,
      },
      {
        id: '2',
        title: 'Mở rộng mạng lưới phân phối',
        description: 'Tìm kiếm và phát triển các đại lý, nhà phân phối mới',
        weight: 30,
        target: '10',
        unit: 'đại lý',
        category: 'Phát triển',
        currentValue: 7,
        completionRate: 70,
      },
      {
        id: '3',
        title: 'Chăm sóc và tái ký kết khách hàng',
        description: 'Duy trì và gia hạn hợp đồng với khách hàng hiện tại',
        weight: 20,
        target: '95',
        unit: '%',
        category: 'Chất lượng',
        currentValue: 88,
        completionRate: 92,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isOnTrack: true,
  },
  {
    id: 'KPI-2026-KI-002',
    employeeId: '1',
    employeeName: 'Trần Văn Bình',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    year: 2026,
    period: 'yearly',
    status: 'pending_manager',
    targets: [
      {
        id: '4',
        title: 'Tăng trưởng doanh thu',
        description: 'Tăng doanh thu so với năm trước',
        weight: 60,
        target: '20',
        unit: '%',
        category: 'Doanh số',
      },
      {
        id: '5',
        title: 'Phát triển sản phẩm mới',
        description: 'Ra mắt sản phẩm mới cho thị trường',
        weight: 40,
        target: '3',
        unit: 'sản phẩm',
        category: 'Phát triển',
      },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
    currentApprover: '2',
  },
  {
    id: 'KPI-2026-KI-003',
    employeeId: '2',
    employeeName: 'Nguyễn Thị Lan',
    department: 'Kinh doanh',
    position: 'Trưởng nhóm',
    year: 2026,
    period: 'yearly',
    status: 'approved',
    targets: [
      {
        id: '6',
        title: 'Quản lý đội nhóm hiệu quả',
        description: 'Đảm bảo hiệu suất làm việc của đội nhóm',
        weight: 100,
        target: '90',
        unit: '%',
        category: 'Quản lý',
        currentValue: 85,
        completionRate: 94,
      },
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
    isOnTrack: true,
  },
  {
    id: 'KPI-2026-MK-001',
    employeeId: '5',
    employeeName: 'Lê Thị C',
    department: 'Marketing',
    position: 'Marketing Executive',
    year: 2026,
    period: 'quarterly',
    status: 'pending_manager',
    targets: [
      {
        id: '7',
        title: 'Tăng số lượng leads',
        description: 'Thu thập leads chất lượng từ các kênh marketing',
        weight: 40,
        target: '500',
        unit: 'leads',
        category: 'Marketing',
      },
      {
        id: '8',
        title: 'Tỷ lệ chuyển đổi',
        description: 'Tăng tỷ lệ chuyển đổi từ leads sang khách hàng',
        weight: 35,
        target: '15',
        unit: '%',
        category: 'Marketing',
      },
      {
        id: '9',
        title: 'Engagement rate',
        description: 'Tăng tương tác trên các kênh social media',
        weight: 25,
        target: '5',
        unit: '%',
        category: 'Marketing',
      },
    ],
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
    submittedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'KPI-2026-MK-002',
    employeeId: '6',
    employeeName: 'Phạm Văn D',
    department: 'Marketing',
    position: 'Content Creator',
    year: 2026,
    period: 'monthly',
    status: 'pending_manager',
    targets: [
      {
        id: '10',
        title: 'Sản xuất nội dung',
        description: 'Tạo nội dung chất lượng cho các kênh marketing',
        weight: 50,
        target: '20',
        unit: 'bài viết',
        category: 'Content',
      },
      {
        id: '11',
        title: 'Reach & Impression',
        description: 'Tăng lượt tiếp cận và hiển thị',
        weight: 50,
        target: '100000',
        unit: 'lượt',
        category: 'Content',
      },
    ],
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    updatedAt: new Date(Date.now() - 21600000).toISOString(),
    submittedAt: new Date(Date.now() - 21600000).toISOString(),
  },
];

// Mock password (same for all users for demo)
export const MOCK_PASSWORD = '1';
