import type { IKPITemplate } from '../../core/models';

export const mockKPITemplates: IKPITemplate[] = [
  // Sales Templates
  {
    id: 'template-001',
    category: 'Doanh số',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    title: 'Đạt doanh số cá nhân',
    description: 'Hoàn thành chỉ tiêu doanh số được giao cho từng quý và cả năm',
    suggestedWeight: 40,
    target: '500 triệu',
    unit: 'VNĐ',
    measurementMethod: 'Tổng giá trị hợp đồng đã ký trong kỳ',
    evaluationCriteria: 'Dựa trên báo cáo doanh số từ hệ thống CRM',
    usageCount: 25,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-002',
    category: 'Phát triển',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    title: 'Mở rộng mạng lưới khách hàng',
    description: 'Tìm kiếm và phát triển các khách hàng mới, đại lý, nhà phân phối',
    suggestedWeight: 30,
    target: '10',
    unit: 'khách hàng',
    measurementMethod: 'Số lượng khách hàng mới được thêm vào hệ thống',
    evaluationCriteria: 'Khách hàng phải có ít nhất 1 đơn hàng thành công',
    usageCount: 20,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-003',
    category: 'Chất lượng',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    title: 'Tỷ lệ chốt đơn',
    description: 'Tăng tỷ lệ chuyển đổi từ leads sang khách hàng thực tế',
    suggestedWeight: 20,
    target: '25',
    unit: '%',
    measurementMethod: 'Số đơn hàng thành công / Tổng số leads',
    evaluationCriteria: 'Tính theo dữ liệu từ hệ thống CRM',
    usageCount: 18,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },

  // Marketing Templates
  {
    id: 'template-004',
    category: 'Marketing',
    department: 'Marketing',
    position: 'Marketing Executive',
    title: 'Tăng số lượng leads',
    description: 'Thu thập leads chất lượng từ các kênh marketing',
    suggestedWeight: 35,
    target: '500',
    unit: 'leads',
    measurementMethod: 'Số lượng leads được thu thập qua các chiến dịch',
    evaluationCriteria: 'Leads phải có thông tin đầy đủ và xác thực',
    usageCount: 15,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-005',
    category: 'Marketing',
    department: 'Marketing',
    position: 'Marketing Executive',
    title: 'Tỷ lệ chuyển đổi',
    description: 'Tăng tỷ lệ chuyển đổi từ leads sang khách hàng',
    suggestedWeight: 30,
    target: '15',
    unit: '%',
    measurementMethod: 'Số khách hàng mua / Tổng số leads',
    evaluationCriteria: 'Theo dõi qua hệ thống CRM và Marketing Automation',
    usageCount: 12,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-006',
    category: 'Content',
    department: 'Marketing',
    position: 'Content Creator',
    title: 'Sản xuất nội dung chất lượng',
    description: 'Tạo nội dung hấp dẫn cho các kênh marketing',
    suggestedWeight: 40,
    target: '20',
    unit: 'bài viết',
    measurementMethod: 'Số lượng bài viết được publish',
    evaluationCriteria: 'Bài viết phải đạt tiêu chuẩn chất lượng và SEO',
    usageCount: 10,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },

  // IT Templates
  {
    id: 'template-007',
    category: 'Phát triển',
    department: 'IT',
    position: 'Developer',
    title: 'Hoàn thành tính năng',
    description: 'Phát triển và hoàn thành các tính năng được giao',
    suggestedWeight: 40,
    target: '10',
    unit: 'tính năng',
    measurementMethod: 'Số tính năng được deploy lên production',
    evaluationCriteria: 'Tính năng phải pass QA và được approve bởi Product Owner',
    usageCount: 8,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-008',
    category: 'Chất lượng',
    department: 'IT',
    position: 'Developer',
    title: 'Code quality score',
    description: 'Duy trì chất lượng code cao',
    suggestedWeight: 25,
    target: '85',
    unit: '%',
    measurementMethod: 'Điểm số từ SonarQube hoặc code review',
    evaluationCriteria: 'Không có critical bugs, maintainability rating A',
    usageCount: 7,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-009',
    category: 'Hiệu suất',
    department: 'IT',
    position: 'Developer',
    title: 'Bug resolution time',
    description: 'Giải quyết bugs nhanh chóng',
    suggestedWeight: 20,
    target: '24',
    unit: 'giờ',
    measurementMethod: 'Thời gian trung bình từ khi bug được report đến khi fix',
    evaluationCriteria: 'Tính theo dữ liệu từ Jira/Bug tracking system',
    usageCount: 6,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },

  // Management Templates
  {
    id: 'template-010',
    category: 'Quản lý',
    department: 'Kinh doanh',
    position: 'Trưởng nhóm',
    title: 'Hiệu suất team',
    description: 'Đảm bảo team đạt KPI tổng thể',
    suggestedWeight: 50,
    target: '90',
    unit: '%',
    measurementMethod: 'Tỷ lệ % KPI của team được hoàn thành',
    evaluationCriteria: 'Trung bình KPI completion rate của tất cả thành viên',
    usageCount: 5,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
  {
    id: 'template-011',
    category: 'Phát triển',
    department: 'Kinh doanh',
    position: 'Trưởng nhóm',
    title: 'Đào tạo và phát triển nhân viên',
    description: 'Nâng cao kỹ năng cho team members',
    suggestedWeight: 30,
    target: '4',
    unit: 'buổi training',
    measurementMethod: 'Số buổi training được tổ chức',
    evaluationCriteria: 'Training phải có feedback tích cực từ nhân viên',
    usageCount: 4,
    isActive: true,
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
    createdBy: 'HR Admin',
  },
];

export const getTemplatesByDepartment = (department: string): IKPITemplate[] => {
  return mockKPITemplates.filter(t => t.department === department && t.isActive);
};

export const getTemplatesByPosition = (position: string): IKPITemplate[] => {
  return mockKPITemplates.filter(t => t.position === position && t.isActive);
};

export const getTemplatesByCategory = (category: string): IKPITemplate[] => {
  return mockKPITemplates.filter(t => t.category === category && t.isActive);
};

export const getPopularTemplates = (limit: number = 5): IKPITemplate[] => {
  return [...mockKPITemplates]
    .filter(t => t.isActive)
    .sort((a, b) => b.usageCount - a.usageCount)
    .slice(0, limit);
};
