import type { IUser, IKPIRecord } from '../../core/models';

// Mock Users
export const mockUsers: IUser[] = [
  {
    id: '1',
    username: 'employee1@gmail.com',
    name: 'Trần Văn Bình',
    role: 'employee',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    managerId: '2',
    managerName: 'Nguyễn Thị Lan',
    token: 'mock-token-employee-1',
    isActive: true,
  },
  {
    id: '2',
    username: 'tl1@gmail.com',
    name: 'Nguyễn Thị Lan',
    role: 'tl',
    department: 'Kinh doanh',
    position: 'Trưởng nhóm Kinh doanh',
    managerId: '3',
    managerName: 'Lê Văn Hùng',
    teamMembers: ['1', '5'],
    token: 'mock-token-tl-1',
    isActive: true,
  },
  {
    id: '3',
    username: 'gl1@gmail.com',
    name: 'Lê Văn Hùng',
    role: 'gl',
    department: 'Kinh doanh',
    position: 'Giám đốc Kinh doanh',
    managerId: '4',
    managerName: 'Phạm Minh Tuấn',
    teamMembers: ['2', '6'],
    token: 'mock-token-gl-1',
    isActive: true,
  },
  {
    id: '4',
    username: 'ceo1@gmail.com',
    name: 'Phạm Minh Tuấn',
    role: 'ceo',
    department: 'Ban Giám đốc',
    position: 'CEO',
    teamMembers: ['3', '7', '8'],
    token: 'mock-token-ceo-1',
    isActive: true,
  },
  {
    id: '5',
    username: 'employee2@gmail.com',
    name: 'Hoàng Thị Mai',
    role: 'employee',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    managerId: '2',
    managerName: 'Nguyễn Thị Lan',
    token: 'mock-token-employee-2',
    isActive: true,
  },
  {
    id: '6',
    username: 'tl2@gmail.com',
    name: 'Đỗ Văn Nam',
    role: 'tl',
    department: 'Marketing',
    position: 'Trưởng nhóm Marketing',
    managerId: '3',
    managerName: 'Lê Văn Hùng',
    teamMembers: ['9', '10'],
    token: 'mock-token-tl-2',
    isActive: true,
  },
];

// Mock KPI Records
export const mockKPIRecords: IKPIRecord[] = [
  {
    id: 'KPI-2026-KI-001',
    employeeId: '1',
    employeeName: 'Trần Văn Bình',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    managerId: '2',
    managerName: 'Nguyễn Thị Lan',
    year: 2026,
    quarter: 1,
    period: 'quarterly',
    status: 'in_progress',
    targets: [
      {
        id: '1',
        title: 'Đạt doanh số cá nhân quý 1',
        description: 'Hoàn thành chỉ tiêu doanh số được giao cho quý 1',
        weight: 50,
        target: '500 triệu',
        unit: 'VNĐ',
        category: 'Doanh số',
        tasks: [
          {
            id: 'task-1-1',
            title: 'Liên hệ 20 khách hàng tiềm năng',
            description: 'Gọi điện và gửi email giới thiệu sản phẩm',
            deadline: '2026-03-15',
            status: 'verified',
            completedAt: '2026-03-10',
            verifiedAt: '2026-03-10',
            verifiedBy: '2',
            evidenceMessage: 'Đã liên hệ 22 khách hàng, có 15 khách quan tâm',
          },
          {
            id: 'task-1-2',
            title: 'Chốt 5 hợp đồng mới',
            description: 'Ký kết hợp đồng với khách hàng mới',
            deadline: '2026-03-20',
            status: 'pending_verify',
            completedAt: '2026-03-10',
            evidenceMessage: 'Đã chốt 3 hợp đồng, tổng giá trị 180 triệu. Link: drive.google.com/contracts',
          },
          {
            id: 'task-1-3',
            title: 'Tái ký hợp đồng với 10 khách hàng cũ',
            deadline: '2026-03-25',
            status: 'to_do',
          },
        ],
      },
      {
        id: '2',
        title: 'Mở rộng mạng lưới phân phối',
        description: 'Tìm kiếm và phát triển các đại lý, nhà phân phối mới',
        weight: 30,
        target: '10',
        unit: 'đại lý',
        category: 'Phát triển',
        tasks: [
          {
            id: 'task-2-1',
            title: 'Khảo sát thị trường khu vực miền Bắc',
            deadline: '2026-03-12',
            status: 'verified',
            completedAt: '2026-03-08',
            verifiedAt: '2026-03-09',
            verifiedBy: '2',
          },
          {
            id: 'task-2-2',
            title: 'Ký kết 5 đại lý mới',
            deadline: '2026-03-30',
            status: 'to_do',
          },
        ],
      },
      {
        id: '3',
        title: 'Chăm sóc và tái ký kết khách hàng',
        description: 'Duy trì và gia hạn hợp đồng với khách hàng hiện tại',
        weight: 20,
        target: '95',
        unit: '%',
        category: 'Chất lượng',
        tasks: [
          {
            id: 'task-3-1',
            title: 'Gọi điện chăm sóc 50 khách hàng hiện tại',
            deadline: '2026-03-18',
            status: 'to_do',
          },
        ],
      },
    ],
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date().toISOString(),
    submittedAt: new Date(Date.now() - 518400000).toISOString(),
    isOnTrack: true,
  },
  {
    id: 'KPI-2026-KI-002',
    employeeId: '2',
    employeeName: 'Nguyễn Thị Lan',
    department: 'Kinh doanh',
    position: 'Trưởng nhóm',
    managerId: '3',
    managerName: 'Lê Văn Hùng',
    year: 2026,
    period: 'quarterly',
    quarter: 1,
    status: 'in_progress',
    targets: [
      {
        id: '4',
        title: 'Quản lý đội nhóm đạt KPI',
        description: 'Đảm bảo 80% nhân viên trong team hoàn thành KPI',
        weight: 60,
        target: '80',
        unit: '%',
        category: 'Quản lý',
        tasks: [
          {
            id: 'task-4-1',
            title: 'Họp 1-1 với từng nhân viên',
            deadline: '2026-03-15',
            status: 'verified',
            completedAt: '2026-03-12',
            verifiedAt: '2026-03-13',
            verifiedBy: '3',
          },
          {
            id: 'task-4-2',
            title: 'Review tiến độ team hàng tuần',
            deadline: '2026-03-31',
            status: 'to_do',
          },
        ],
      },
      {
        id: '5',
        title: 'Phát triển kỹ năng cho team',
        description: 'Tổ chức training và coaching',
        weight: 40,
        target: '4',
        unit: 'buổi',
        category: 'Phát triển',
        tasks: [
          {
            id: 'task-5-1',
            title: 'Tổ chức training kỹ năng bán hàng',
            deadline: '2026-03-20',
            status: 'to_do',
          },
        ],
      },
    ],
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    updatedAt: new Date().toISOString(),
    submittedAt: new Date(Date.now() - 432000000).toISOString(),
    isOnTrack: true,
  },
  {
    id: 'KPI-2026-KI-003',
    employeeId: '5',
    employeeName: 'Hoàng Thị Mai',
    department: 'Kinh doanh',
    position: 'Nhân viên kinh doanh',
    managerId: '2',
    managerName: 'Nguyễn Thị Lan',
    year: 2026,
    quarter: 1,
    period: 'quarterly',
    status: 'pending_approval',
    targets: [
      {
        id: '6',
        title: 'Tăng doanh số khu vực phía Nam',
        description: 'Mở rộng thị trường miền Nam',
        weight: 100,
        target: '300 triệu',
        unit: 'VNĐ',
        category: 'Doanh số',
        tasks: [
          {
            id: 'task-6-1',
            title: 'Khảo sát 30 khách hàng tiềm năng',
            deadline: '2026-03-25',
            status: 'to_do',
          },
          {
            id: 'task-6-2',
            title: 'Chốt 3 hợp đồng lớn',
            deadline: '2026-03-31',
            status: 'to_do',
          },
        ],
      },
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
    currentApprover: '2',
  },
];

// Mock password (same for all users for demo)
export const MOCK_PASSWORD = '1';
